In [1]:
import numpy as np

## 1D with numpy

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  1
Shape of t :  (7,)


.ndim : numpy의 차원을 출력
.shape : numpy의 크기를 출력  (7,)은 (1,7)을 의미함.

In [6]:
f't[0] t[1] t[-1] = {t[0]} {t[1]} {t[-1]}'

't[0] t[1] t[-1] = 0.0 1.0 6.0'

numpy에서는 범위를 지정하여 원소를 가져올 수 있습니다. 이를 slicing이라고 합니다. "배열\[시작번호 : 끝번호\]"를 지정하면 끝번호를 제외한 범위의 원소를 가져옵니다.

In [9]:
print(t[2:5])
print(t[4:-1])

[2. 3. 4.]
[4. 5.]


In [10]:
print(f't[:2] t[3:] = {t[:2]} {t[3:]}')

t[:2] t[3:] = [0. 1.] [3. 4. 5. 6.]


## 2D with numpy

In [13]:
t = np.array([ [(j+1.0)*(i+1.0) for j in range(3)] for i in range(4)])
print(t)

[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6.  9.]
 [ 4.  8. 12.]]


In [14]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)


Rank  of t:  2
Shape of t:  (4, 3)


# 파이토치 텐서

파이토치의 텐서는 numpy와 매우 유사하지만 더 좋습니다.

In [17]:
import torch

In [19]:
t = torch.FloatTensor([float(i) for i in range(7)])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [22]:
print(t.dim())  # 차원
print(t.shape)  # 크기
print(t.size()) # 크기

1
torch.Size([7])
torch.Size([7])


파이토치에서도 슬라이싱을 제공합니다. 사용은 numpy와 동일합니다.

In [25]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2],t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D with PyTorch

In [26]:
t = torch.FloatTensor([ [(j+1.0)*(i+1.0) for j in range(3)] for i in range(4)])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.]])


In [27]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [30]:
print(t[:,1])       # 모든 첫번째 차원에서 두번째 차원의 첫번째 원소만 가져온다.
print(t[:,1].size())

tensor([2., 4., 6., 8.])
torch.Size([4])


In [31]:
print(t[:,:-1])     # 모든 첫번째 차원에서 두번째 차원의 마지막 원소를 제외하고 모두 가져온다.

tensor([[1., 2.],
        [2., 4.],
        [3., 6.],
        [4., 8.]])


## 브로드캐스팅

두 행렬 A, B가 있습니다. 행렬의 덧셈과 뺄셈을 할 때는 두 행렬 A, B의 크기가 동일해야 된다고 배웠습니다. 하지만 딥러닝에서는 그렇지 못한 경우가 발생합니다. 이때 자동으로 크기를 맞춰서 연산해주는 것이 브로드캐스팅입니다.

In [34]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


m1과 m2의 크기는 둘다 (1,2)이므로 문제 없이 덧셈 연산이 가능합니다. 이번에는 크기가 다른 텐서들 간의 연산을 해보겠습니다.

In [37]:
m1 = torch.FloatTensor([[1,2]]) # vector
m2 = torch.FloatTensor([3])     # scalar
print(m1 + m2)
print(m1.size() , m2.size())

tensor([[4., 5.]])
torch.Size([1, 2]) torch.Size([1])


결과를 보듯이 m2가 (1,2) 차원으로 변경되어 연산이 수행된 것을 알 수 있습니다.

In [38]:
m1 = torch.FloatTensor([[1, 2]])    # 2,1 vector
m2 = torch.FloatTensor([[3], [4]])  # 1,2 vector
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


두 벡터는 수학적으로 연산이 불가능합니다. 파이토치에서는 두 벡터를 (2,2) 크기로 변경하여 연산되었습니다.

```
[1, 2]
==> [[1, 2],
     [1, 2]]
[3],[4]
==> [[3, 3],
     [4, 4]]
```

브로드캐스팅은 이처럼 크기가 다른 두 텐서를 연산할 수 있다는 점에서 좋지만, 반대로 두 텐서의 크기가 다른지 모른 상태로 어떠한 에러가 없다면 의도치 않은 결과를 낼 것입니다. 그리고 이러한 오류가 어디서 발생했는지 알 수 없을 것 입니다.

# 주요 사용되는 기능

## 행렬 곱셈과 곱셈의 차이

행렬로 곱셈을 하는 방법은 크게 두가지가 있습니다. 행렬 곱셈과 원소 별 곱셈입니다. 파이토치 텐서의 행렬 곱셈을 보겠습니다. 이를 matmul()을 통해 수행합니다.

In [40]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


행렬 곱셈 이외에도 element-wise 곱셈이 있습니다. 이는 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것을 말합니다. 여기서는 브로드캐스팅이 된후에 element-wise 곱셈이 수행되는 것을 보여줍니다. 이를 * 또는 mat()을 통해 수행합니다.

In [41]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


m1 행렬의 크기는 (2,2) 였습니다. m2 행렬의 크기는 (2,1)였습니다. 이때 element-wise 곱세을 수행하면, 두 행렬의 크기는 브로드캐스팅된 후에 곱셈이 수행됩니다.

```
[1]
[2]
==> [[1, 1],
     [2, 2]]
```

## 평균

평균을 구하는 방법은 쉽습니다. .mean()을 사용하여 원소의 평균을 구합니다.

In [43]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [49]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=-1), t.mean(dim=1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000]) tensor([1.5000, 3.5000])


## 덧셈

덧셈은 평균 연산과 연산 방법이나 인자가 의미하는 바는 정확히 동일합니다. 다만 평균이 아니라 덧셈을 할 뿐입니다.

In [51]:
t = torch.FloatTensor([[1,2,],[3,4]])
print(t.sum())
print(t.sum(dim =0))
print(t.sum(dim =1))
print(t.sum(dim =-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## 최대와 아그맥스(ArgMax)

최대는 원소의 최대값을 리턴하고, 아그맥스는(ArgMax)는 최대값을 가진 인덱스를 리턴합니다.

In [60]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.max())

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


In [59]:
print(t.max(dim=0))
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [62]:
print(f"max : {t.max(dim=0)[0]}")
print(f"arg max : {t.max(dim=0)[1]}")

max : tensor([3., 4.])
arg max : tensor([1, 1])
